// Districts.js

// This file contains the master list of all city locations and the data for each district.

const hiredHelpSubTable = [
    { dice: 1, name: 'Hired Help: Brutes & Brawlers' },
    { dice: 2, name: 'Hired Help: Cloak & Dagger' },
    { dice: 3, name: 'Hired Help: Bows & Slings' },
    { dice: 4, name: 'Hired Help: Scribes & Clerks' },
    { dice: 5, name: 'Hired Help: Guides & Trackers' },
    { dice: 6, name: 'Hired Help: Caravan & Mount' },
    { dice: 7, name: 'Hired Help: Arcane Academics' },
    { dice: 8, name: 'Hired Help: Magic Mercenaries' },
    { dice: 9, name: 'Hired Help: Priestly Guidance' },
    { dice: 10, name: 'Hired Help: Hands of the Divine' },
];

const magicShopSubTable = [
    { dice: 1, name: 'Magic Shop - Armor' },
    { dice: 2, name: 'Magic Shop - Books' },
    { dice: 3, name: 'Magic Shop - Clothing' },
    { dice: 4, name: 'Magic Shop - Jewelry' },
    { dice: 5, name: 'Magic Shop - Weapons' },
    { dice: 6, name: 'Magic Shop - Misc. & Curiosities' },
];

// --- FIXED ---
// The 'additionalLocationRollsCount' variable was used in SetGen.js but never defined.
// It is now defined here as a map of city size to the number of rolls.
// The unused 'additionalLocationRollsTable' has been removed for clarity.
const additionalLocationRollsCount = {
    'Very Small': 1,
    'Small': 2,
    'Medium': 3,
    'Large': 4,
    'Very Large': 5,
};


// Master list of all possible locations
const allCityLocations = {
    'Baker': { name: 'Baker', category: 'shop' },
    'Tailor': { name: 'Tailor', category: 'shop' },
    'Alchemist': { name: 'Alchemist', category: 'shop' },
    'Cobbler': { name: 'Cobbler', category: 'shop' },
    'Luxury Furnishings': { name: 'Luxury Furnishings', category: 'shop' },
    'Rare Libations & Fare': { name: 'Rare Libations & Fare', category: 'shop' },
    'Barber': { name: 'Barber', category: 'service' },
    'Bathhouse': { name: 'Bathhouse', category: 'service' },
    'Doctor/Apothecary': { name: 'Doctor/Apothecary', category: 'service' },
    'House of Leisure': { name: 'House of Leisure', category: 'service' },
    'Inn': { name: 'Inn', category: 'service' },
    'Club': { name: 'Club', category: 'service' },
    'Tavern': { name: 'Tavern', category: 'service' },
    'Hired Help': { name: 'Hired Help', category: 'service', subTable: hiredHelpSubTable },
    'Archives/Library': { name: 'Archives/Library', category: 'non-commercial' },
    'Academy/University': { name: 'Academy/University', category: 'non-commercial' },
    'Schoolhouse': { name: 'Schoolhouse', category: 'non-commercial' },
    'Amphitheater': { name: 'Amphitheater', category: 'non-commercial' },
    'General Store': { name: 'General Store', category: 'shop' },
    'Weaver': { name: 'Weaver', category: 'shop' },
    'Artist': { name: 'Artist', category: 'shop' },
    'Rare Botanicals': { name: 'Rare Botanicals', category: 'shop' },
    'Magic Shop': { name: 'Magic Shop', category: 'shop', subTable: magicShopSubTable },
    'Soothsayer': { name: 'Soothsayer', category: 'service' },
    'Hired Help: Arcane Academics': { name: 'Hired Help: Arcane Academics', category: 'service' },
    'Hired Help: Magic Mercenaries': { name: 'Hired Help: Magic Mercenaries', category: 'service' },
    'Forum': { name: 'Forum', category: 'non-commercial' },
    'Lodge': { name: 'Lodge', category: 'non-commercial' },
    'Hired Help: Guides & Trackers': { name: 'Hired Help: Guides & Trackers', category: 'service' },
    'Outdoor Recreational Area': { name: 'Outdoor Recreational Area', category: 'non-commercial' },
    'Dance Hall': { name: 'Dance Hall', category: 'non-commercial' },
    'Altar': { name: 'Altar', category: 'non-commercial' },
    'Cooper': { name: 'Cooper', category: 'shop' },
    'Carpenter': { name: 'Carpenter', category: 'shop' },
    'Thatcher': { name: 'Thatcher', category: 'shop' },
    'Wainwright': { name: 'Wainwright', category: 'shop' },
    'Armorsmith': { name: 'Armorsmith', category: 'shop' },
    'Bank & Exchange': { name: 'Bank & Exchange', category: 'shop' },
    'Foundry/Smelting': { name: 'Foundry/Smelting', category: 'shop' },
    'Miller': { name: 'Miller', category: 'shop' },
    'Textile Production': { name: 'Textile Production', category: 'shop' },
    'Shipwright': { name: 'Shipwright', category: 'shop' },
    'Rare Trade Goods': { name: 'Rare Trade Goods', category: 'shop' },
    'Weaponsmith': { name: 'Weaponsmith', category: 'shop' },
    'Smithy': { name: 'Smithy', category: 'shop' },
    'Stable': { name: 'Stable', category: 'service' },
    'Treasury': { name: 'Treasury', category: 'non-commercial' },
    'Gathering Hall': { name: 'Gathering Hall', category: 'non-commercial' },
    'Hired Help: Scribes and Clerks': { name: 'Hired Help: Scribes and Clerks', category: 'service' },
    'Courthouse': { name: 'Courthouse', category: 'non-commercial' },
    'Chancery': { name: 'Chancery', category: 'non-commercial' },
    'Town Hall': { name: 'Town Hall', category: 'non-commercial' },
    'Hired Help: Priestly Guidance': { name: 'Hired Help: Priestly Guidance', category: 'service' },
    'Hired Help: Hands of the Divine': { name: 'Hired Help: Hands of the Divine', category: 'service' },
    'Magic Shop - Books': { name: 'Magic Shop - Books', category: 'shop' },
    'Butcher': { name: 'Butcher', category: 'shop' },
    'Magic Shop - Misc. & Curiosities': { name: 'Magic Shop - Misc. & Curiosities', category: 'shop' },
    'Temple': { name: 'Temple', category: 'non-commercial' },
    'Great Temple': { name: 'Great Temple', category: 'non-commercial' },
};


const districtData = {
    'Administration': {
        includedLocations: [
            'Courthouse', 'Chancery', 'Town Hall', 'Treasury',
            'Hired Help: Scribes and Clerks'
        ],
        additionalLocationsTable: [
            { min: 1, max: 1, name: 'Reroll (Quality Down)', quality: -1 },
            { min: 2, max: 2, name: 'Baker' },
            { min: 3, max: 3, name: 'Tailor' },
            { min: 4, max: 4, name: 'Alchemist' },
            { min: 5, max: 5, name: 'Cobbler' },
            { min: 6, max: 6, name: 'Luxury Furnishings' },
            { min: 7, max: 7, name: 'Rare Libations & Fare' },
            { min: 8, max: 8, name: 'Barber' },
            { min: 9, max: 9, name: 'Bathhouse' },
            { min: 10, max: 10, name: 'Doctor/Apothecary' },
            { min: 11, max: 11, name: 'House of Leisure' },
            { min: 12, max: 12, name: 'Inn' },
            { min: 13, max: 13, name: 'Club' },
            { min: 14, max: 14, name: 'Tavern' },
            { min: 15, max: 15, name: 'Hired Help', subTable: hiredHelpSubTable },
            { min: 16, max: 16, name: 'Archives/Library' },
            { min: 17, max: 17, name: 'Academy/University' },
            { min: 18, max: 18, name: 'Schoolhouse' },
            { min: 19, max: 19, name: 'Amphitheater' },
            { min: 20, max: 20, name: 'Reroll (Quality Up)', quality: 1 },
        ]
    },
    'Arcane': {
        includedLocations: [
            'Archives/Library', 'Academy/University', 'Magic Shop', 'Magic Shop',
            'Hired Help: Arcane Academics', 'Hired Help: Magic Mercenaries'
        ],
        additionalLocationsTable: [
            { min: 1, max: 1, name: 'Reroll (Quality Down)', quality: -1 },
            { min: 2, max: 2, name: 'General Store' },
            { min: 3, max: 3, name: 'Tailor' },
            { min: 4, max: 4, name: 'Weaver' },
            { min: 5, max: 5, name: 'Alchemist' },
            { min: 6, max: 6, name: 'Artist' },
            { min: 7, max: 7, name: 'Rare Botanicals' },
            { min: 8, max: 9, name: 'Magic Shop', subTable: magicShopSubTable },
            { min: 10, max: 10, name: 'Barber' },
            { min: 11, max: 11, name: 'Soothsayer' },
            { min: 12, max: 12, name: 'House of Leisure' },
            { min: 13, max: 13, name: 'Club' },
            { min: 14, max: 14, name: 'Tavern' },
            { min: 15, max: 15, name: 'Hired Help: Arcane Academics' },
            { min: 16, max: 16, name: 'Hired Help: Magic Mercenaries' },
            { min: 17, max: 17, name: 'Forum' },
            { min: 18, max: 18, name: 'Schoolhouse' },
            { min: 19, max: 19, name: 'Lodge' },
            { min: 20, max: 20, name: 'Reroll (Quality Up)', quality: 1 },
        ]
    },
    'Botanical': {
        includedLocations: [ 'Outdoor Recreational Area', 'Inn', 'Stable' ],
        additionalLocationsTable: [
            { min: 1, max: 1, name: 'Reroll (Quality Down)', quality: -1 },
            { min: 2, max: 2, name: 'Baker' },
            { min: 3, max: 3, name: 'Tailor' },
            { min: 4, max: 4, name: 'Weaver' },
            { min: 5, max: 5, name: 'Alchemist' },
            { min: 6, max: 6, name: 'Artist' },
            { min: 7, max: 7, name: 'Cobbler' },
            { min: 8, max: 8, name: 'Rare Botanicals' },
            { min: 9, max: 9, name: 'Rare Libations & Fare' },
            { min: 10, max: 10, name: 'Magic Shop', subTable: magicShopSubTable },
            { min: 11, max: 11, name: 'Doctor/Apothecary' },
            { min: 12, max: 12, name: 'House of Leisure' },
            { min: 13, max: 13, name: 'Inn' },
            { min: 14, max: 14, name: 'Soothsayer' },
            { min: 15, max: 15, name: 'Tavern' },
            { min: 16, max: 16, name: 'Hired Help: Guides & Trackers' },
            { min: 17, max: 17, name: 'Outdoor Recreational Area' },
            { min: 18, max: 18, name: 'Dance Hall' },
            { min: 19, max: 19, name: 'Altar' },
            { min: 20, max: 20, name: 'Reroll (Quality Up)', quality: 1 },
        ]
    },
     'Craft': {
        includedLocations: ['Smithy', 'Carpenter', 'General Store', 'Tailor', 'Magic Shop'],
        additionalLocationsTable: [
            { min: 1, max: 1, name: 'Reroll (Quality Down)', quality: -1 },
            { min: 2, max: 2, name: 'Cooper' },
            { min: 3, max: 3, name: 'Carpenter' },
            { min: 4, max: 4, name: 'Thatcher' },
            { min: 5, max: 5, name: 'Wainwright' },
            { min: 6, max: 6, name: 'Armorsmith' },
            { min: 7, max: 7, name: 'Artist' },
            { min: 8, max: 8, name: 'Bank & Exchange' },
            { min: 9, max: 9, name: 'Cobbler' },
            { min: 10, max: 10, name: 'Foundry/Smelting' },
            { min: 11, max: 11, name: 'Miller' },
            { min: 12, max: 12, name: 'Textile Production' },
            { min: 13, max: 13, name: 'Shipwright' }, // Reroll if not near water
            { min: 14, max: 14, name: 'Magic Shop', subTable: magicShopSubTable },
            { min: 15, max: 15, name: 'Luxury Furnishings' },
            { min: 16, max: 16, name: 'Rare Trade Goods' },
            { min: 17, max: 17, name: 'Weaponsmith' },
            { min: 18, max: 18, name: 'Tavern' },
            { min: 19, max: 19, name: 'Hired Help', subTable: hiredHelpSubTable },
            { min: 20, max: 20, name: 'Reroll (Quality Up)', quality: 1 },
        ]
    },
    'Docks': {
        includedLocations: ['Shipwright', 'Weaver', 'House of Leisure', 'Inn', 'Tavern'],
        additionalLocationsTable: [
            { min: 1, max: 1, name: 'Reroll (Quality Down)', quality: -1 },
            { min: 2, max: 2, name: 'Cooper' },
            { min: 3, max: 3, name: 'Carpenter' },
            { min: 4, max: 4, name: 'Smithy' },
            { min: 5, max: 5, name: 'Bank & Exchange' },
            { min: 6, max: 6, name: 'Shipwright' },
            { min: 7, max: 7, name: 'Rare Botanicals' },
            { min: 8, max: 8, name: 'Rare Libations & Fare' },
            { min: 9, max: 10, name: 'Magic Shop', subTable: magicShopSubTable },
            { min: 11, max: 11, name: 'Barber' },
            { min: 12, max: 12, name: 'Bathhouse' },
            { min: 13, max: 13, name: 'Doctor/Apothecary' },
            { min: 14, max: 14, name: 'House of Leisure' },
            { min: 15, max: 15, name: 'Inn' },
            { min: 16, max: 16, name: 'Club' },
            { min: 17, max: 17, name: 'Tavern' },
            { min: 18, max: 18, name: 'Hired Help', subTable: hiredHelpSubTable },
            { min: 19, max: 19, name: 'Altar' },
            { min: 20, max: 20, name: 'Reroll (Quality Up)', quality: 1 },
        ]
    },
    'Industrial': {
        includedLocations: [
            'Smithy', 
            { subTable: [{dice: 1, name: 'Foundry/Smelting'}, {dice: 2, name: 'Textile Production'}, {dice: 3, name: 'Miller'}] }
        ],
        additionalLocationsTable: [
            { min: 1, max: 1, name: 'Reroll (Quality Down)', quality: -1 },
            { min: 2, max: 2, name: 'Cooper' },
            { min: 3, max: 3, name: 'Carpenter' },
            { min: 4, max: 4, name: 'General Store' },
            { min: 5, max: 5, name: 'Smithy' },
            { min: 6, max: 6, name: 'Tailor' },
            { min: 7, max: 7, name: 'Thatcher' },
            { min: 8, max: 8, name: 'Wainwright' },
            { min: 9, max: 9, name: 'Weaver' },
            { min: 10, max: 10, name: 'Miller' },
            { min: 11, max: 11, name: 'Foundry/Smelting' },
            { min: 12, max: 12, name: 'Textile Production' },
            { min: 13, max: 13, name: 'Shipwright' }, 
            { min: 14, max: 14, name: 'House of Leisure' },
            { min: 15, max: 15, name: 'Club' },
            { min: 16, max: 16, name: 'Tavern' },
            { min: 17, max: 17, name: 'Hired Help', subTable: hiredHelpSubTable },
            { min: 18, max: 18, name: 'Gathering Hall' },
            { min: 19, max: 19, name: 'Treasury' },
            { min: 20, max: 20, name: 'Reroll (Quality Up)', quality: 1 },
        ]
    },
    'Market': {
        includedLocations: ['Baker', 'Butcher', 'General Store', 'Smithy', 'Tailor'],
        additionalLocationsTable: [
            { min: 1, max: 1, name: 'Reroll (Quality Down)', quality: -1 },
            { min: 2, max: 2, name: 'Wainwright' },
            { min: 3, max: 3, name: 'Weaver' },
            { min: 4, max: 4, name: 'Alchemist' },
            { min: 5, max: 5, name: 'Artist' },
            { min: 6, max: 6, name: 'Bank & Exchange' },
            { min: 7, max: 7, name: 'Cobbler' },
            { min: 8, max: 8, name: 'Rare Botanicals' },
            { min: 9, max: 9, name: 'Luxury Furnishings' },
            { min: 10, max: 10, name: 'Rare Libations & Fare' },
            { min: 11, max: 11, name: 'Rare Trade Goods' },
            { min: 12, max: 12, name: 'Magic Shop', subTable: magicShopSubTable },
            { min: 13, max: 13, name: 'Barber' },
            { min: 14, max: 14, name: 'Inn' },
            { min: 15, max: 15, name: 'Club' },
            { min: 16, max: 16, name: 'Soothsayer' },
            { min: 17, max: 17, name: 'Stable' },
            { min: 18, max: 18, name: 'Tavern' },
            { min: 19, max: 19, name: 'Hired Help', subTable: hiredHelpSubTable },
            { min: 20, max: 20, name: 'Reroll (Quality Up)', quality: 1 },
        ]
    },
    'Merchant': {
        includedLocations: ['Bank & Exchange', 'Tailor', 'Artist', 'Cobbler', 'Magic Shop - Misc. & Curiosities'],
        additionalLocationsTable: [
            { min: 1, max: 1, name: 'Reroll (Quality Down)', quality: -1 },
            { min: 2, max: 2, name: 'General Store' },
            { min: 3, max: 3, name: 'Wainwright' },
            { min: 4, max: 4, name: 'Alchemist' },
            { min: 5, max: 5, name: 'Artist' },
            { min: 6, max: 6, name: 'Bank & Exchange' },
            { min: 7, max: 7, name: 'Cobbler' },
            { min: 8, max: 8, name: 'Luxury Furnishings' },
            { min: 9, max: 9, name: 'Rare Libations & Fare' },
            { min: 10, max: 10, name: 'Rare Trade Goods' },
            { min: 11, max: 12, name: 'Magic Shop', subTable: magicShopSubTable },
            { min: 13, max: 13, name: 'Barber' },
            { min: 14, max: 14, name: 'Bathhouse' },
            { min: 15, max: 15, name: 'House of Leisure' },
            { min: 16, max: 16, name: 'Inn' },
            { min: 17, max: 17, name: 'Club' },
            { min: 18, max: 18, name: 'Tavern' },
            { min: 19, max: 19, name: 'Hired Help', subTable: hiredHelpSubTable },
            { min: 20, max: 20, name: 'Reroll (Quality Up)', quality: 1 },
        ]
    },
    'Scholar': {
        includedLocations: ['Archives/Library', 'Academy/University', 'Forum', 'Schoolhouse', 'Hired Help: Scribes and Clerks'],
        additionalLocationsTable: [
            { min: 1, max: 1, name: 'Reroll (Quality Down)', quality: -1 },
            { min: 2, max: 2, name: 'General Store' },
            { min: 3, max: 3, name: 'Tailor' },
            { min: 4, max: 4, name: 'Thatcher' },
            { min: 5, max: 5, name: 'Alchemist' },
            { min: 6, max: 6, name: 'Weaver' },
            { min: 7, max: 7, name: 'Bank & Exchange' },
            { min: 8, max: 8, name: 'Rare Botanicals' },
            { min: 9, max: 9, name: 'Luxury Furnishings' },
            { min: 10, max: 10, name: 'Rare Trade Goods' },
            { min: 11, max: 11, name: 'Magic Shop - Books' },
            { min: 12, max: 12, name: 'Doctor/Apothecary' },
            { min: 13, max: 13, name: 'Hired Help: Scribes and Clerks' },
            { min: 14, max: 14, name: 'Archives/Library' },
            { min: 15, max: 15, name: 'Barber' },
            { min: 16, max: 16, name: 'Academy/University' },
            { min: 17, max: 17, name: 'Forum' },
            { min: 18, max: 18, name: 'Schoolhouse' },
            { min: 19, max: 19, name: 'Gathering Hall' },
            { min: 20, max: 20, name: 'Reroll (Quality Up)', quality: 1 },
        ]
    },
    'Slums': {
        includedLocations: ['Butcher', 'House of Leisure', 'Inn', 'Tavern'],
        additionalLocationsTable: [
            { min: 1, max: 1, name: 'Reroll (Quality Down)', quality: -1 },
            { min: 2, max: 2, name: 'Baker' },
            { min: 3, max: 3, name: 'Butcher' },
            { min: 4, max: 4, name: 'General Store' },
            { min: 5, max: 5, name: 'Smithy' },
            { min: 6, max: 6, name: 'Thatcher' },
            { min: 7, max: 7, name: 'Weaver' },
            { min: 8, max: 8, name: 'Alchemist' },
            { min: 9, max: 9, name: 'Foundry/Smelting' },
            { min: 10, max: 10, name: 'Miller' },
            { min: 11, max: 11, name: 'Textile Production' },
            { min: 12, max: 12, name: 'Bathhouse' },
            { min: 13, max: 13, name: 'Barber' },
            { min: 14, max: 14, name: 'Doctor/Apothecary' },
            { min: 15, max: 15, name: 'House of Leisure' },
            { min: 16, max: 16, name: 'Inn' },
            { min: 17, max: 17, name: 'Club' },
            { min: 18, max: 18, name: 'Soothsayer' },
            { min: 19, max: 19, name: 'Tavern' },
            { min: 20, max: 20, name: 'Reroll (Quality Up)', quality: 1 },
        ]
    },
    'Temple': {
        includedLocations: [
            { subTable: [{dice: 1, name: 'Temple'}, {dice: 2, name: 'Great Temple'}, {dice: 3, name: 'Archives/Library'}] },
            'Hired Help: Priestly Guidance', 
            'Hired Help: Hands of the Divine'
        ],
        additionalLocationsTable: [
            { min: 1, max: 1, name: 'Reroll (Quality Down)', quality: -1 },
            { min: 2, max: 2, name: 'Cooper' },
            { min: 3, max: 3, name: 'Carpenter' },
            { min: 4, max: 4, name: 'Tailor' },
            { min: 5, max: 5, name: 'Alchemist' },
            { min: 6, max: 6, name: 'Artist' },
            { min: 7, max: 7, name: 'Bank & Exchange' },
            { min: 8, max: 8, name: 'Rare Botanicals' },
            { min: 9, max: 9, name: 'Rare Libations & Fare' },
            { min: 10, max: 10, name: 'Magic Shop', subTable: magicShopSubTable },
            { min: 11, max: 11, name: 'Barber' },
            { min: 12, max: 12, name: 'Bathhouse' },
            { min: 13, max: 13, name: 'Doctor/Apothecary' },
            { min: 14, max: 14, name: 'Inn' },
            { min: 15, max: 15, name: 'Soothsayer' },
            { min: 16, max: 16, name: 'Tavern' },
            { min: 17, max: 17, name: 'Hired Help', subTable: [{dice: 1, name: 'Hired Help: Priestly Guidance'}, {dice: 2, name: 'Hired Help: Hands of the Divine'}] },
            { min: 18, max: 18, name: 'Schoolhouse' },
            { min: 19, max: 19, name: 'Amphitheater' },
            { min: 20, max: 20, name: 'Reroll (Quality Up)', quality: 1 },
        ]
    },
    'Upper Class': {
        includedLocations: ['Bank & Exchange', 'Baker', 'Tailor', 'Luxury Furnishings', 'Doctor/Apothecary'],
        additionalLocationsTable: [
            { min: 1, max: 1, name: 'Reroll (Quality Down)', quality: -1 },
            { min: 2, max: 2, name: 'Butcher' },
            { min: 3, max: 3, name: 'Tailor' },
            { min: 4, max: 4, name: 'Weaver' },
            { min: 5, max: 5, name: 'Alchemist' },
            { min: 6, max: 6, name: 'Artist' },
            { min: 7, max: 7, name: 'Cobbler' },
            { min: 8, max: 8, name: 'Rare Botanicals' },
            { min: 9, max: 9, name: 'Luxury Furnishings' },
            { min: 10, max: 10, name: 'Rare Libations & Fare' },
            { min: 11, max: 11, name: 'Magic Shop', subTable: magicShopSubTable },
            { min: 12, max: 12, name: 'Barber' },
            { min: 13, max: 13, name: 'Bathhouse' },
            { min: 14, max: 14, name: 'House of Leisure' },
            { min: 15, max: 15, name: 'Inn' },
            { min: 16, max: 16, name: 'Club' },
            { min: 17, max: 17, name: 'Soothsayer' },
            { min: 18, max: 18, name: 'Stable' },
            { min: 19, max: 19, name: 'Tavern' },
            { min: 20, max: 20, name: 'Reroll (Quality Up)', quality: 1 },
        ]
    }
};

export {
    allCityLocations,
    districtData,
    additionalLocationRollsCount,
};